### PR TITLE
[ FEAT ] RePallet for CPL

### PR DESCRIPTION
**Pull request by coreyd303**

### CODE REVIEW

**Comment by ShepBook** [comment]
Since we use ```<% css_class = request.subdomain == "chipublib" ? "btn-mustard" : "" %>``` all throughout the place, maybe that could live as some place more general? I know there's been talk of making colors customized on other sites as they come in. Maybe we could have something in the application_controller that sets an instance variable we can use anywhere we need this ```css_class```?

It would also just generally clean things up and save probably a couple dozen lines of code we wouldn't need anymore. What do you think?

**Comment by coreyd303** [comment]
Yep good, I could move this to application.html.erb

**Comment by ShepBook** [comment]
Just a heads up, unless you refactored things, the namespacing has the issue of using different layouts for a lot of places. Unfortunately, I remember having an issue with ```application.html.erb``` not actually being rendered in all places.

If it's not globally used as a layout, you could just set it as a variable in the application controller and then pull it on any request that passes through there.

**Comment by coreyd303** [comment]
placed in application_helper to be globally avaliable

**Pull request merged**
